apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: caspereijkens/fastapi:0.0.6
        imagePullPolicy: Always
        name: blog
        ports:
        - containerPort: 80